### ISSUE TITLE
Example Not Running

### ISSUE THREAD

**Issue by timmcarson** [AppliedAcousticsChalmers/acoustics-hardware#7]
I was trying to run the "measurement_single_microphone.ipynb" example but it appears to be out of date.  

I tried changing "devices" to "interfaces" and then changed the generator.

`generator = acoustics_hardware.generators.SweepGenerator(lower_frequency=50, upper_frequency=20e3, sweep_length=sweep_duration, repetitions=1, amplitude=amplitude_lin)`

can you provide an updated example or am I doing something wrong?

thanks

**Comment by HaHeho** [comment]
Yes, those versions of the examples might not be maintained well. I have extended their functionality substantially in a separate branch https://github.com/AppliedAcousticsChalmers/acoustics-hardware/tree/add-notebook-SMA-example.

I would recommend you to checkout that branch. The examples there provide more convenience and functionality during the measurement process. It also uses a different Python API (`sounddevice`), which is more for the capture of general purpose acoustic measurements (i.e. less specifically tailored towards Carl's reason to implement this toolbox in the first place). However, the code base in my branch may be incompatible to the main branch, and there is probably no plan to merge them anytime soon. But this shouldn't be a problem for simple acoustic measurements, as my updated example notebooks are self-containted and well documented.

**Comment by HaHeho** [comment]
@timmcarson did this resolve your problem?

Will close the thread. Feel free to re-open.
